### ISSUE TITLE
aria-labelledby implementation

### ISSUE THREAD

**Issue by svinkle** [scottaohara/aria-switch-button#2]
Just wondering why bother with `aria-labelledby`? Seems like everything else is nice and dynamic, but this part may generate some friction on implementation. 

I might suggest changing it to an `aria-label` and add a simple instruction of, "This is what the switch will be called. Add the name here." Something like that. 🙂

Awesome work, btw!

**Comment by scottaohara** [comment]
it's a weird thing, i know.

when i was writing that part, i just kept thinking of all the situations, on real projects, where I use either solution. The labelledby would be preferred so as not to repeat content / having discrepancies between visual and aria labeling.  

meh.  i'm going to think about this some more.

but thanks again :)
